apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: kingdon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
