apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- flux-sync.yaml
images:
#  - name: ghcr.io/fluxcd/kustomize-controller
#    newName: stefanprodan/kustomize-controller
#    newTag: ssa-fix1
#  - name: ghcr.io/fluxcd/source-controller
#    newName: kingdonb/source-controller
#    newTag: 382e812
patches:
#  - target:
#      version: v1
#      group: apps
#      kind: Deployment
#      name: kustomize-controller
#      namespace: flux-system
#    patch: |-
#      - op: add
#        path: /spec/template/spec/containers/0/args/-
#        value: --requeue-dependency=15s
#  - target:
#      version: v1
#      group: apps
#      kind: Deployment
#      name: kustomize-controller
#      namespace: flux-system
#    patch: |-
#      - op: add
#        path: /spec/template/spec/containers/0/args/-
#        value: --requeue-dependency=15s
#patchesStrategicMerge:
#- |-
#  apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#  kind: Kustomization
#  metadata:
#    name: flux-system
#    namespace: flux-system
#  spec:
#    interval: 1m
#    patches:
#    - target:
#        version: v1
#        group: apps
#        kind: Deployment
#        name: notification-controller
#        namespace: flux-system
#      patch: |-
#        - op: add
#          path: /spec/template/spec/containers/0/args/-
#          value: --rate-limit-interval=10s
#    - target:
#        version: v1
#        group: apps
#        kind: Deployment
#        name: kustomize-controller
#        namespace: flux-system
#      patch: |-
#        - op: add
#          path: /spec/template/spec/containers/0/args/-
#          value: --requeue-dependency=15s
#        - op: add
#          path: /spec/template/spec/containers/0/args/0
#          value: --concurrent=6
#        - op: replace
#          path: /spec/template/spec/containers/0/resources/limits/cpu
#          value: "2"
#        - op: replace
#          path: /spec/template/spec/containers/0/resources/limits/memory
#          value: "2Gi"
