apiVersion: v1
kind: Secret
metadata:
    name: magalix-agent
    namespace: kube-system
    labels:
        app.kubernetes.io/name: magalix-agent
        app.kubernetes.io/version: "1"
        app.kubernetes.io/component: secret
        app.kubernetes.io/tier: backend
type: Opaque
data:
    ACCOUNT_ID: ENC[AES256_GCM,data:Xj5iij3Cy4yqHwmmczwYAIvMYBGJLoORhtX6Hg/TH1iO7oRfLBmK2d3eud+prBx5,iv:ko5nL7UbDKcCPXHo6dYdDmGHHz/uonTuTB/uZpaGqeM=,tag:JnF+vM+V9nOdC95+GCvqnA==,type:str]
    CLUSTER_ID: ENC[AES256_GCM,data:vQk1UUdkefVDEpMrncjJ/VPo39/KxWaBsdkUZx5SwfmyjnfrhwRyDMH7q5wQzWxN,iv:j64/hRnOAptVxl3LIEcgwL89dXJwZD7T9S1u10ydLHs=,tag:sbQu5eepL8+/m6j3zvZ1AA==,type:str]
    SECRET: ENC[AES256_GCM,data:btva2IKqcdk61p4c1nV+1HS+wuzJQdqrfbMs0y7AEaUq2Jy+yXGfcDXl+pkeLA90/RwdlAg7Avq4OXIp1EqdqUZeHQor16XyAEWbjM+GekQtMzI77K1RCAGq5W23AbmBihT0eArR7BBGlOHnuKe4jNasVJDPTZDb5bWAo/q+GyXVEX8pYqDXQa2qV58Xetn5v2+4yuHshCmHi7zAUBRqLkRryKPNbZyuduYwrp2MJsS3ld7NZtonOQ==,iv:7g4mXqCF01I6ZdJdAT0Kwzzd0JzBqjfGMycGZAZLLNY=,tag:G94WRDvRV9HMPTaQxkTk4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-03T15:45:33Z"
    mac: ENC[AES256_GCM,data:Xr7e96TwRAwcKOgiaunJPO/OU6MNpDtdkP81s3olqkdCxJ1KFw8xxilkWgEo0VOlyYdoPZ5e1VXwHaSRfRHb2kGODkx9tbKfRxtmfkJtsAp/5N9hxrei1pWoQ6yRLM0UOLicHbX9GR9Qqkd7fDlzHYxCCEwA2npbR7pEVMmEUWY=,iv:u7I8z8NL5jUL6apfrGWaWgis5j1X5txbMez3XayzJW8=,tag:+F4Yh5jJPhK3/ktVzzwDFQ==,type:str]
    pgp:
        - created_at: "2022-02-03T15:45:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMARAAl66oF3e5BoZqUXzpfhhf2jwkBLgCnvlh03rC4dJqLwQ/
            +g3KBj9hpkAEuV91TrT1h1WLVlH6jPpSdsjr6LcTJLySfjdWd19luvV9CE+RVEqf
            hGXed+X8DXfM6kEnM3oUGe7B8ThUrtT5lbiC/iJlHdv0ECvZjcnpyMLifizkqbYc
            eh4kRiqOouGok8XiZWx9ewovQFtQmlKBB1LFju4GDdy64ESZ5URJFm/udhq7eJ+t
            YLWLtwdnUZKdF36bzM1+y3cyyKPyGVHCVMYS0NrSufJ90etMqZ6TAhQNmY6RAEK+
            VK/3ZUOnMxPtTHfohsXPywEY/kL4FeKKfyp7ylJO1rmNBm9iJNS8EbpsLxtZZfYc
            C4KM3PkqK5dDReFojK5DldPSBXY3tORmrPcOCB5t2oVkXBy6QVJmeMRZuC58P6Pp
            s5M3+/YdmXNibDWF5QioDxTWMWsBPODEX5GfSU4T+8W3ocy9fDZV2x52ae95/bgj
            Im5nlujGXcosawRfTwxGLiRhubpdlbHcSTe1v9TWCkPjhOWjpGk1/F94hLUonJQE
            YlZdAFoFQ6/DyywQeXAaDdGAk3i/nXNDwrBoVt9ROls1pt5pvwEDZ4ep/M7u81sP
            IHQf95bvVC/QpE+KrUNU744ncV75oPOCPCTGzhusv2fmj42ID5yIaaID0pNua9HS
            XAHL4N+S6XfCNTlHoLB0n3I/Ovh4Cb9vVK/LqosZb1vHQXfSZNQjvC0nc0O+/ozb
            3g7TKcodJojwnj2QI8kxP+SSvlBJoKgKUHzD4OPfhbmBsLIyhP1ftj8TlRCJ
            =pHem
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
