apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tremolo-kube-oidc-proxy
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/TremoloSecurity/kube-oidc-proxy
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/charts/
