apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 91-harbor
  namespace: flux-system
spec:
  interval: 60m0s
  retryInterval: 6m0s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-sync
  path: ./apps/harbor
  dependsOn:
  - name: 11-certificates
  - name: 12-persistence
  - name: 30-ingress-nginx
  - name: 90-minio-stage
  # - name: traefik-api-crds
  prune: true
  wait: false
  suspend: true
